# Generated by Django 4.0.3 on 2022-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
