# Generated by Django 4.0.3 on 2022-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_category_tag_remove_todo_category_todo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
